spring.application.name=taskmanager

# H2 Database Settings for Local

spring.datasource.driverClassName=org.h2.Driver



spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


# H2 Console enable karne ke liye
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Security bypass karne ke liye (Jo tune pehle kiya tha)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Railway MySQL Config
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=mwUPAbGjBKwCsqIupCtrtTCFrZsBLXKM
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver