spring.application.name=taskmanager

# H2 Database Settings for Local
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console enable karne ke liye
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Security bypass karne ke liye (Jo tune pehle kiya tha)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration